name: multi-docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
      
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
        # user login for speed up
      - run: docker build -t blaxsior/next-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true blaxsior/next-test npm run test
    
  build:
    name: "build all"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t blaxsior/multi-client -f ./client/Dockerfile ./client
      - run: docker build -t blaxsior/multi-nginx -f ./nginx/Dockerfile ./nginx
      - run: docker build -t blaxsior/multi-server -f ./server/Dockerfile ./server
      - run: docker build -t blaxsior/multi-worker -f ./worker/Dockerfile ./worker
## some test!
